name: 'Publish default Laravel Sail images'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Weekly

jobs:
  build-docker-images:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: initializerforlaravel
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: shivammathur/setup-php@7854a0cae7fa7a5f3feac66d27bae2dc42d1067a
        with:
          php-version: '8.1'
      - uses: actions/checkout@v2
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Update Images
        run: 'php artisan initializer:update-sail-images'
